### ISSUE TITLE
打开代理、运行程序后，无法打开小花仙官网，访问其他页面正常

### ISSUE THREAD

**Issue by wowyki** [hxz393/FlashGameStreamline#1]
打开代理、运行程序后，访问小花仙官网如图<img width="1230" alt="Snipaste_2024-04-15_14-11-03" src="https://github.com/hxz393/FlashGameStreamline/assets/163496985/995e637c-4d65-4d79-9b92-eead9a0db9e1">
关闭代理后就能正常打开小花仙页游官网
日志应该是这个！
[run.log](https://github.com/hxz393/FlashGameStreamline/files/14975231/run.log)

**Comment by hxz393** [comment]
看起来代理设置成功，但是没有安装证书。你需要访问 http://mitm.it/ 来安装。见文档。

**Comment by wowyki** [comment]
> 看起来代理设置成功，但是没有安装证书。你需要访问 http://mitm.it/ 来安装。见文档。

我是按照文档一步步来哒，安装证书了的

**Comment by hxz393** [comment]
你还可以试试更换设置里的代理端口号

**Comment by hxz393** [comment]
然后多试几个其他网站，比如百度主页、腾讯主页、淘米主页等等，告诉我访问结果。

**Comment by wowyki** [comment]
之前用的端口是12346，无法访问小花仙官网。现在改成16666，可以访问小花仙官网啦，访问百度主页和淘米主页也正常，访问腾讯主页（https://www.qq.com/）不太正常，具体情况如图。谢谢解答~
![image](https://github.com/hxz393/FlashGameStreamline/assets/163496985/cf37ea01-6796-42e6-98e3-e0764640ccfd)
